spring:
  application:
    name: 313backend
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/remit313}
    username: ${DB_USER:apple}
    password: ${DB_PASS:backend}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:}
  mail:
    host: ${MAIL_HOST:smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USER:test}
    password: ${MAIL_PASS:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  security:
    jwt:
      secret: ${JWT_SECRET:4b676f62594a5043586c554b736b7537535451614741706c6467385a49444f6f437032766f75666f77343d}
      expiration: ${JWT_EXPIRATION_MS:900000} # 15 minutes in ms
      refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7 days in ms
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:"http://localhost:3000,http://localhost:5173"}

---
spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/remit313
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASS}
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 900000
      refresh-expiration: 604800000
  cors:
    allowed-origins: "https://staging.313businesspoints.com"

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/remit313
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASS}
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 900000
      refresh-expiration: 604800000
  cors:
    allowed-origins: "https://313businesspoints.com"
